export const DASHBOARD_OVERVIEW_CARD = {
  BUDGET: "budget",
  SHOPPING: "shopping",
  GIFTS: "gifts",
  MEDICINE_CABINET: "medicine-cabinet",
  WATCHLIST: "watchlist",
  RESTAURANTS: "restaurants",
  BIRTHDAYS: "birthdays",
  CALENDAR: "calendar",
  FAMILY: "family",
} as const;

export const DASHBOARD_OVERVIEW_CARDS = [
  DASHBOARD_OVERVIEW_CARD.BUDGET,
  DASHBOARD_OVERVIEW_CARD.SHOPPING,
  DASHBOARD_OVERVIEW_CARD.GIFTS,
  DASHBOARD_OVERVIEW_CARD.MEDICINE_CABINET,
  DASHBOARD_OVERVIEW_CARD.WATCHLIST,
  DASHBOARD_OVERVIEW_CARD.RESTAURANTS,
  DASHBOARD_OVERVIEW_CARD.BIRTHDAYS,
  DASHBOARD_OVERVIEW_CARD.CALENDAR,
  DASHBOARD_OVERVIEW_CARD.FAMILY,
] as const;

export type DashboardOverviewCardId = (typeof DASHBOARD_OVERVIEW_CARDS)[number];

export const DEFAULT_DASHBOARD_OVERVIEW_ORDER: DashboardOverviewCardId[] = [
  ...DASHBOARD_OVERVIEW_CARDS,
];
