export const NIMBUS_TOUR_ID = {
  INTRO: "intro",
  FAMILY: "family",
  SETTINGS_SOLO: "settingsSolo",
  NOTIFICATIONS: "notifications",
  BUDGET: "budget",
  SHOPPING: "shopping",
  GIFTS: "gifts",
  BIRTHDAYS: "birthdays",
  SCHEDULE: "schedule",
  MEDICINE: "medicine",
  WATCHLIST: "watchlist",
  RESTAURANTS: "restaurants",
  PETS: "pets",
  CHORES: "chores",
  NOTES: "notes",
  FAMILY_CALENDAR: "familyCalendar",
} as const;

export type NimbusTourId = (typeof NIMBUS_TOUR_ID)[keyof typeof NIMBUS_TOUR_ID];

export const NIMBUS_TOUR_TARGET = {
  DASHBOARD_GREETING: "dashboard-greeting",
  DASHBOARD_VIEW_TABS: "dashboard-view-tabs",
  DASHBOARD_ATTENTION: "dashboard-attention",
  DASHBOARD_ATTENTION_PIN: "dashboard-attention-pin",
  DASHBOARD_OVERVIEW: "dashboard-overview",
  DASHBOARD_LAYOUT_EDIT: "dashboard-layout-edit",
  DASHBOARD_MODULES: "dashboard-modules",
  MOBILE_MODULES_SHEET: "mobile-modules-sheet",
  MOBILE_MODULES_NAV: "mobile-modules-nav",
  DASHBOARD_TODAY: "dashboard-today",
  GLOBAL_SEARCH_TRIGGER: "global-search-trigger",
  SETTINGS_NAV: "settings-nav",
  SETTINGS_PROFILE: "settings-profile",
  SETTINGS_JOIN_FAMILY: "settings-join-family",
  SETTINGS_CREATE_FAMILY: "settings-create-family",
  SETTINGS_ACCOUNT_TYPE: "settings-account-type",
  SETTINGS_SHOPPING_CATEGORIES: "settings-shopping-categories",
  SETTINGS_PASSWORD: "settings-password",
  SETTINGS_NOTIFICATIONS: "settings-notifications",
  NOTIFICATIONS_HEADER: "notifications-header",
  NOTIFICATIONS_FILTERS: "notifications-filters",
  NOTIFICATIONS_LIST: "notifications-list",
  BUDGET_HEADER: "budget-header",
  BUDGET_ADD: "budget-add",
  BUDGET_LISTS: "budget-lists",
  BUDGET_HIDDEN: "budget-hidden",
  BUDGET_DETAIL: "budget-detail",
  BUDGET_INCOME: "budget-income",
  BUDGET_FILTERS: "budget-filters",
  BUDGET_EXPORT: "budget-export",
  BUDGET_WATCH: "budget-watch",
  SHOPPING_HEADER: "shopping-header",
  SHOPPING_ADD: "shopping-add",
  SHOPPING_LISTS: "shopping-lists",
  SHOPPING_ITEMS: "shopping-items",
  SHOPPING_CATEGORIES: "shopping-categories",
  SHOPPING_WATCH: "shopping-watch",
  SHOPPING_ADD_ITEM: "shopping-add-item",
  GIFTS_HEADER: "gifts-header",
  GIFTS_ADD: "gifts-add",
  GIFTS_FILTERS: "gifts-filters",
  GIFTS_LIST: "gifts-list",
  BIRTHDAYS_HEADER: "birthdays-header",
  BIRTHDAYS_ADD: "birthdays-add",
  BIRTHDAYS_CALENDAR: "birthdays-calendar",
  BIRTHDAYS_LIST: "birthdays-list",
  SCHEDULE_HEADER: "schedule-header",
  SCHEDULE_ADD: "schedule-add",
  SCHEDULE_MULTIDAY: "schedule-multiday",
  SCHEDULE_CALENDAR: "schedule-calendar",
  SCHEDULE_LIST: "schedule-list",
  SCHEDULE_PRINT: "schedule-print",
  MEDICINE_HEADER: "medicine-header",
  MEDICINE_ADD: "medicine-add",
  MEDICINE_FILTERS: "medicine-filters",
  MEDICINE_LIST: "medicine-list",
  WATCHLIST_HEADER: "watchlist-header",
  WATCHLIST_ADD: "watchlist-add",
  WATCHLIST_PLATFORMS: "watchlist-platforms",
  WATCHLIST_FILTERS: "watchlist-filters",
  WATCHLIST_STATUS: "watchlist-status",
  WATCHLIST_LIST: "watchlist-list",
  RESTAURANTS_HEADER: "restaurants-header",
  RESTAURANTS_ADD: "restaurants-add",
  RESTAURANTS_FILTERS: "restaurants-filters",
  RESTAURANTS_LIST: "restaurants-list",
  PETS_HEADER: "pets-header",
  PETS_ADD: "pets-add",
  PETS_CARE: "pets-care",
  PETS_FILTERS: "pets-filters",
  PETS_LIST: "pets-list",
  CHORES_HEADER: "chores-header",
  CHORES_ADD: "chores-add",
  CHORES_ASSIGN: "chores-assign",
  CHORES_RECURRENCE: "chores-recurrence",
  CHORES_VIEW_TOGGLE: "chores-view-toggle",
  CHORES_FILTERS: "chores-filters",
  CHORES_LIST: "chores-list",
  NOTES_HEADER: "notes-header",
  NOTES_ADD: "notes-add",
  NOTES_PIN: "notes-pin",
  NOTES_VISIBILITY: "notes-visibility",
  NOTES_CATEGORY: "notes-category",
  NOTES_FILTERS: "notes-filters",
  NOTES_LIST: "notes-list",
  FAMILY_CALENDAR_HEADER: "family-calendar-header",
  FAMILY_CALENDAR_VIEW: "family-calendar-view",
  TOUR_SUMMARY: "tour-summary",
  FAMILY_SETTINGS_TAB: "family-settings-tab",
  FAMILY_MEMBERS: "family-members",
  FAMILY_PERMISSIONS: "family-permissions",
  FAMILY_LEAVE: "family-leave",
  FAMILY_REALTIME: "family-realtime",
} as const;

export const NIMBUS_PATH_TOUR: Record<string, NimbusTourId> = {
  "/budget": NIMBUS_TOUR_ID.BUDGET,
  "/shopping": NIMBUS_TOUR_ID.SHOPPING,
  "/gifts": NIMBUS_TOUR_ID.GIFTS,
  "/birthdays": NIMBUS_TOUR_ID.BIRTHDAYS,
  "/schedule": NIMBUS_TOUR_ID.SCHEDULE,
  "/calendar": NIMBUS_TOUR_ID.FAMILY_CALENDAR,
  "/medicine-cabinet": NIMBUS_TOUR_ID.MEDICINE,
  "/watchlist": NIMBUS_TOUR_ID.WATCHLIST,
  "/restaurants": NIMBUS_TOUR_ID.RESTAURANTS,
  "/pets": NIMBUS_TOUR_ID.PETS,
  "/chores": NIMBUS_TOUR_ID.CHORES,
  "/notes": NIMBUS_TOUR_ID.NOTES,
  "/notifications": NIMBUS_TOUR_ID.NOTIFICATIONS,
  "/family": NIMBUS_TOUR_ID.FAMILY,
};

export function getModuleTourIdForPath(pathname: string): NimbusTourId | null {
  return NIMBUS_PATH_TOUR[pathname] ?? null;
}
