export const NOTIFICATION_TYPE = {
  BIRTHDAY_ADDED: "birthday_added",
  BIRTHDAY_UPDATED: "birthday_updated",
  BIRTHDAY_DELETED: "birthday_deleted",
  SCHEDULE_ADDED: "schedule_added",
  SCHEDULE_UPDATED: "schedule_updated",
  SCHEDULE_DELETED: "schedule_deleted",
  GIFT_ADDED: "gift_added",
  GIFT_UPDATED: "gift_updated",
  GIFT_DELETED: "gift_deleted",
  SHOPPING_LIST_ADDED: "shopping_list_added",
  SHOPPING_LIST_UPDATED: "shopping_list_updated",
  SHOPPING_LIST_DELETED: "shopping_list_deleted",
  SHOPPING_LIST_ITEM_ADDED: "shopping_list_item_added",
  SHOPPING_LIST_ITEM_REMOVED: "shopping_list_item_removed",
} as const;

export type NotificationType = (typeof NOTIFICATION_TYPE)[keyof typeof NOTIFICATION_TYPE];

export const BIRTHDAY_NOTIFICATION_TYPES: NotificationType[] = [
  NOTIFICATION_TYPE.BIRTHDAY_ADDED,
  NOTIFICATION_TYPE.BIRTHDAY_UPDATED,
  NOTIFICATION_TYPE.BIRTHDAY_DELETED,
];

export const SCHEDULE_NOTIFICATION_TYPES: NotificationType[] = [
  NOTIFICATION_TYPE.SCHEDULE_ADDED,
  NOTIFICATION_TYPE.SCHEDULE_UPDATED,
  NOTIFICATION_TYPE.SCHEDULE_DELETED,
];

export const GIFT_NOTIFICATION_TYPES: NotificationType[] = [
  NOTIFICATION_TYPE.GIFT_ADDED,
  NOTIFICATION_TYPE.GIFT_UPDATED,
  NOTIFICATION_TYPE.GIFT_DELETED,
];

export const SHOPPING_LIST_NOTIFICATION_TYPES: NotificationType[] = [
  NOTIFICATION_TYPE.SHOPPING_LIST_ADDED,
  NOTIFICATION_TYPE.SHOPPING_LIST_UPDATED,
  NOTIFICATION_TYPE.SHOPPING_LIST_DELETED,
  NOTIFICATION_TYPE.SHOPPING_LIST_ITEM_ADDED,
  NOTIFICATION_TYPE.SHOPPING_LIST_ITEM_REMOVED,
];

export const NOTIFICATION_FILTER_TAB = {
  ALL: "all",
  UNREAD: "unread",
  READ: "read",
} as const;

export type NotificationFilterTab =
  (typeof NOTIFICATION_FILTER_TAB)[keyof typeof NOTIFICATION_FILTER_TAB];

export const NOTIFICATIONS_PAGE_SIZE = 10;
