export const NOTIFICATION_TYPE = {
  BIRTHDAY_ADDED: "birthday_added",
  BIRTHDAY_UPDATED: "birthday_updated",
  BIRTHDAY_DELETED: "birthday_deleted",
  SCHEDULE_ADDED: "schedule_added",
  SCHEDULE_UPDATED: "schedule_updated",
  SCHEDULE_DELETED: "schedule_deleted",
  GIFT_ADDED: "gift_added",
  GIFT_UPDATED: "gift_updated",
  GIFT_DELETED: "gift_deleted",
  SHOPPING_LIST_ADDED: "shopping_list_added",
  SHOPPING_LIST_UPDATED: "shopping_list_updated",
  SHOPPING_LIST_DELETED: "shopping_list_deleted",
  SHOPPING_LIST_ITEM_ADDED: "shopping_list_item_added",
  SHOPPING_LIST_ITEM_REMOVED: "shopping_list_item_removed",
  BUDGET_ADDED: "budget_added",
  BUDGET_UPDATED: "budget_updated",
  BUDGET_DELETED: "budget_deleted",
  BUDGET_EXPENSE_ADDED: "budget_expense_added",
  BUDGET_EXPENSE_REMOVED: "budget_expense_removed",
  BUDGET_INCOME_ADDED: "budget_income_added",
  BUDGET_INCOME_REMOVED: "budget_income_removed",
  BUDGET_EXPENSE_DUE_REMINDER: "budget_expense_due_reminder",
  MEDICINE_ADDED: "medicine_added",
  MEDICINE_UPDATED: "medicine_updated",
  MEDICINE_DELETED: "medicine_deleted",
  MEDICINE_EXPIRING: "medicine_expiring",
  WATCHLIST_ADDED: "watchlist_added",
  WATCHLIST_UPDATED: "watchlist_updated",
  WATCHLIST_DELETED: "watchlist_deleted",
  RESTAURANT_ADDED: "restaurant_added",
  RESTAURANT_UPDATED: "restaurant_updated",
  RESTAURANT_DELETED: "restaurant_deleted",
  PET_ADDED: "pet_added",
  PET_CARE_ADDED: "pet_care_added",
  PET_CARE_UPDATED: "pet_care_updated",
  PET_CARE_DELETED: "pet_care_deleted",
  CHORE_ADDED: "chore_added",
  CHORE_UPDATED: "chore_updated",
  CHORE_DELETED: "chore_deleted",
  NOTE_ADDED: "note_added",
  NOTE_UPDATED: "note_updated",
  NOTE_DELETED: "note_deleted",
} as const;

export type NotificationType = (typeof NOTIFICATION_TYPE)[keyof typeof NOTIFICATION_TYPE];

export const BIRTHDAY_NOTIFICATION_TYPES: NotificationType[] = [
  NOTIFICATION_TYPE.BIRTHDAY_ADDED,
  NOTIFICATION_TYPE.BIRTHDAY_UPDATED,
  NOTIFICATION_TYPE.BIRTHDAY_DELETED,
];

export const SCHEDULE_NOTIFICATION_TYPES: NotificationType[] = [
  NOTIFICATION_TYPE.SCHEDULE_ADDED,
  NOTIFICATION_TYPE.SCHEDULE_UPDATED,
  NOTIFICATION_TYPE.SCHEDULE_DELETED,
];

export const GIFT_NOTIFICATION_TYPES: NotificationType[] = [
  NOTIFICATION_TYPE.GIFT_ADDED,
  NOTIFICATION_TYPE.GIFT_UPDATED,
  NOTIFICATION_TYPE.GIFT_DELETED,
];

export const SHOPPING_LIST_NOTIFICATION_TYPES: NotificationType[] = [
  NOTIFICATION_TYPE.SHOPPING_LIST_ADDED,
  NOTIFICATION_TYPE.SHOPPING_LIST_UPDATED,
  NOTIFICATION_TYPE.SHOPPING_LIST_DELETED,
  NOTIFICATION_TYPE.SHOPPING_LIST_ITEM_ADDED,
  NOTIFICATION_TYPE.SHOPPING_LIST_ITEM_REMOVED,
];

export const BUDGET_NOTIFICATION_TYPES: NotificationType[] = [
  NOTIFICATION_TYPE.BUDGET_ADDED,
  NOTIFICATION_TYPE.BUDGET_UPDATED,
  NOTIFICATION_TYPE.BUDGET_DELETED,
  NOTIFICATION_TYPE.BUDGET_EXPENSE_ADDED,
  NOTIFICATION_TYPE.BUDGET_EXPENSE_REMOVED,
  NOTIFICATION_TYPE.BUDGET_INCOME_ADDED,
  NOTIFICATION_TYPE.BUDGET_INCOME_REMOVED,
  NOTIFICATION_TYPE.BUDGET_EXPENSE_DUE_REMINDER,
];

export const MEDICINE_NOTIFICATION_TYPES: NotificationType[] = [
  NOTIFICATION_TYPE.MEDICINE_ADDED,
  NOTIFICATION_TYPE.MEDICINE_UPDATED,
  NOTIFICATION_TYPE.MEDICINE_DELETED,
  NOTIFICATION_TYPE.MEDICINE_EXPIRING,
];

export const WATCHLIST_NOTIFICATION_TYPES: NotificationType[] = [
  NOTIFICATION_TYPE.WATCHLIST_ADDED,
  NOTIFICATION_TYPE.WATCHLIST_UPDATED,
  NOTIFICATION_TYPE.WATCHLIST_DELETED,
];

export const RESTAURANT_NOTIFICATION_TYPES: NotificationType[] = [
  NOTIFICATION_TYPE.RESTAURANT_ADDED,
  NOTIFICATION_TYPE.RESTAURANT_UPDATED,
  NOTIFICATION_TYPE.RESTAURANT_DELETED,
];

export const PET_NOTIFICATION_TYPES: NotificationType[] = [
  NOTIFICATION_TYPE.PET_ADDED,
  NOTIFICATION_TYPE.PET_CARE_ADDED,
  NOTIFICATION_TYPE.PET_CARE_UPDATED,
  NOTIFICATION_TYPE.PET_CARE_DELETED,
];

export const CHORE_NOTIFICATION_TYPES: NotificationType[] = [
  NOTIFICATION_TYPE.CHORE_ADDED,
  NOTIFICATION_TYPE.CHORE_UPDATED,
  NOTIFICATION_TYPE.CHORE_DELETED,
];

export const NOTE_NOTIFICATION_TYPES: NotificationType[] = [
  NOTIFICATION_TYPE.NOTE_ADDED,
  NOTIFICATION_TYPE.NOTE_UPDATED,
  NOTIFICATION_TYPE.NOTE_DELETED,
];

export const NOTIFICATION_FILTER_TAB = {
  ALL: "all",
  UNREAD: "unread",
  READ: "read",
} as const;

export type NotificationFilterTab =
  (typeof NOTIFICATION_FILTER_TAB)[keyof typeof NOTIFICATION_FILTER_TAB];

export const NOTIFICATIONS_PAGE_SIZE = 10;
