/** Domyślne (PL) teksty UI używane w asercjach E2E. */
export const t = {
  login: {
    title: "Witaj z powrotem",
    submit: "Zaloguj się",
    errorInvalid: "Nieprawidłowy email lub hasło.",
    passwordChangedTitle: "Hasło zostało zmienione",
  },
  register: {
    title: "Załóż rodzinne konto",
    submit: "Zarejestruj się bezpłatnie",
    successTitle: "Sprawdź swoją skrzynkę!",
    errorPasswordMatch: "Hasła nie są identyczne.",
    errorPasswordLength: "Hasło musi mieć co najmniej 8 znaków.",
  },
  onboarding: {
    title: "Stwórz swój profil",
    colorTitle: "Wybierz kolor avatara",
    nameTitle: "Jak masz na imię?",
    accountTitle: "Jak chcesz korzystać z Nimbusly?",
    joinFamilyTitle: "Dołącz do rodziny",
    familyTitle: "Stwórz rodzinę",
    inviteCodeLabel: "Kod zaproszenia",
    soloTitle: "Konto solo",
    next: "Dalej",
    back: "Wstecz",
    finish: "Wejdź do panelu",
  },
  dashboard: {
    greeting: "Dzień dobry",
    modules: "Moduły",
    logout: "Wyloguj",
    logoutConfirmTitle: "Wylogować się?",
    moduleLabels: [
      "Budżet",
      "Zakupy",
      "Prezenty",
      "Apteczka",
      "Filmy i seriale",
      "Restauracje i puby",
      "Zwierzęta",
      "Obowiązki domowe",
      "Notatki",
      "Urodziny",
      "Grafik",
      "Rodzina",
    ],
  },
  account: {
    menuProfile: "Profil i avatar",
    menuAccountType: "Typ konta",
    menuFamily: "Zarządzaj rodziną",
    menuPermissions: "Uprawnienia",
    familyInviteCode: "Kod zaproszenia",
    familyInviteSend: "Wyślij zaproszenie",
    familyInviteEmailLabel: "Zaproś na email",
    menuPassword: "Zmień hasło",
    settingsTitle: "Ustawienia konta",
    accountTypeFixedDesc:
      "Typ konta wybierasz przy zakładaniu konta. Aby dołączyć do rodziny lub założyć własną, skorzystaj z opcji poniżej. Aby opuścić rodzinę, przejdź do zakładki „Zarządzaj rodziną”.",
    permissionsMembersTitle: "Członkowie i role",
    leaveFamilyBtn: "Opuść rodzinę",
    save: "Zapisz",
    profileSaved: "Profil został zaktualizowany.",
    changePasswordBtn: "Wyślij link na email",
    changePasswordSuccessTitle: "Sprawdź swoją skrzynkę!",
    changePasswordSuccessMessage:
      "Wysłaliśmy link do zmiany hasła. Kliknij go w mailu, aby ustawić nowe hasło.",
    breadcrumbDashboard: "Panel",
  },
  nav: {
    login: "Zaloguj się",
    getStarted: "Zacznij za darmo",
  },
  gifts: {
    title: "Prezenty",
    subtitle:
      "Pomysły na prezenty w formie notatek — solo lub współdzielone z rodziną.",
    addBtn: "Dodaj pomysł",
    addTitle: "Nowy pomysł na prezent",
  },
  notes: {
    title: "Notatki",
    subtitle: "Twórz kategorie z emoji i zapisuj notatki — solo lub współdzielone z rodziną.",
    addBtn: "Dodaj notatkę",
    addTitle: "Nowa notatka",
  },
  chores: {
    title: "Obowiązki domowe",
    subtitle: "Zadania z terminami, przypisaniem i powtarzalnością — solo lub z rodziną.",
    addBtn: "Dodaj zadanie",
    addTitle: "Nowe zadanie",
  },
  medicineCabinet: {
    title: "Domowa apteczka",
    subtitle: "Leki w domu — termin ważności, ilość i dostępność. Solo lub współdzielone z rodziną.",
    addBtn: "Dodaj lek",
    addTitle: "Nowy lek",
  },
  pets: {
    title: "Zwierzęta",
    subtitle: "Profile pupili, szczepienia, wizyty u weterynarza i zapasy — solo lub z rodziną.",
    addBtn: "Dodaj zwierzę",
    addTitle: "Nowe zwierzę",
  },
  modules: {
    budget: "Budżet",
    shopping: "Listy zakupów",
    gifts: "Prezenty",
    birthdays: "Urodziny",
    schedule: "Grafik pracy",
    medicineCabinet: "Domowa apteczka",
    watchlist: "Filmy i seriale",
    restaurants: "Restauracje i puby",
    pets: "Zwierzęta",
    chores: "Obowiązki domowe",
    notes: "Notatki",
  },
} as const;
